### ISSUE TITLE
Crash on PNG

### ISSUE THREAD

**Issue by grizzly** [jie-cao/SwiftImage#6]
let imageWithAlpha = UIImage(CGImage:imageRefWithAlpha!);

causes

<Error>: CGBitmapContextCreate: unsupported parameter combination: 8 integer bits/component; 40 bits/pixel; 4-component color space; kCGImageAlphaPremultipliedFirst; 5120 bytes/row.

and then

fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by grizzly** [comment]
FIX: for "public class func decodImage(image:UIImage, scale: CGFloat) -> UIImage?"

```
      if let imageRefWithAlpha = CGBitmapContextCreateImage(context) {
         return  UIImage(CGImage:imageRefWithAlpha);

    }
    return nil;
```

**Comment by jie-cao** [comment]
Thanks for finding this issue. I fixed the issue in a similar way.
